# Generated by Django 5.2.5 on 2025-09-22 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="task",
        ),
    ]
