# Generated by Django 5.2.5 on 2025-09-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_remove_website_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
