# Generated by Django 5.2.5 on 2025-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0004_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="proposals",
            field=models.JSONField(default=list),
        ),
    ]
