# Generated by Django 5.2.5 on 2025-09-25 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0005_alter_match_proposals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="search.match")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
