# Generated by Django 5.2.5 on 2025-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
