# Generated by Django 5.2.5 on 2025-10-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0007_notification_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
