# Generated by Django 5.2.5 on 2025-10-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0008_alter_website_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name="Outline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("content", models.TextField()),
                (
                    "notification",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="search.notification"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
