# Generated by Django 5.2.5 on 2025-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0009_alter_notification_email_outline"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="owner",
            field=models.EmailField(
                blank=True, help_text="Debug outline will be sent to this email.", max_length=254, null=True
            ),
        ),
    ]
