# Generated by Django 5.2.5 on 2025-10-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0010_outline_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="notification",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="outline", to="search.notification"
            ),
        ),
    ]
