# Generated by Django 5.2.5 on 2025-10-01 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0011_alter_outline_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="title",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="outline",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="outline", to="search.notification"
            ),
        ),
    ]
