# Generated by Django 5.2.5 on 2025-10-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0012_outline_title_alter_outline_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outline",
            name="owner",
        ),
        migrations.AddField(
            model_name="notification",
            name="owner",
            field=models.EmailField(
                blank=True, help_text="Debug outline will be sent to this email.", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="outline",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="outlines", to="search.notification"
            ),
        ),
    ]
