# Generated by Django 5.2.5 on 2025-10-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0013_remove_outline_owner_notification_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="ready",
            field=models.BooleanField(
                default=False, help_text="Indicates whether outlines, i.e. one-pagers are prepared."
            ),
        ),
    ]
