# Generated by Django 5.2.5 on 2025-10-02 17:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0014_notification_ready"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(default="Workflow", max_length=255)),
                ("problem", models.TextField(help_text="The name of the problem to be solved by this Workflow.")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("model", models.CharField(default="gemini-2.5-pro", max_length=128)),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Controls randomness of generation (0.0 = deterministic, 1.0 = maximum randomness).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "return_variable",
                    models.CharField(
                        blank=True,
                        help_text="The name of the variable that stores the return text from the LLM. Can be used throughout Workflow.",  # noqa: E501
                        max_length=128,
                        null=True,
                        verbose_name="Variable Name",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="search.workflow",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
