# Generated by Django 5.2.5 on 2025-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0015_workflow_prompt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterField(
            model_name="prompt",
            name="return_variable",
            field=models.CharField(
                blank=True,
                help_text="The name of the variable that stores the return text from the LLM. Workflow scoped.",
                max_length=128,
                null=True,
                verbose_name="Variable Name",
            ),
        ),
    ]
