# Generated by Django 5.2.5 on 2025-10-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0016_alter_prompt_options_alter_prompt_return_variable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="website",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="search.website",
            ),
        ),
    ]
