# Generated by Django 5.2.5 on 2025-11-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0014_alter_opportunity_link"),
        ("search", "0017_alter_match_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="outline",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outlines",
                to="opportunity.opportunity",
            ),
        ),
    ]
