# Generated by Django 5.2.5 on 2025-11-05 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0018_outline_opportunity"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEmailBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to override the default main section of the outline email for this notification.",
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        help_text="Custom HTML for the main section. Django template syntax is supported. You can use placeholders like {{ grants_list_html }} and {{ calendly_link }}.",
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_block",
                        to="search.notification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
