# Generated by Django 5.2.5 on 2025-11-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0019_notificationemailblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="test",
            field=models.BooleanField(
                default=False, help_text="Indicates whether this website was created for testing purposes."
            ),
        ),
    ]
