# Generated by Django 5.2.5 on 2025-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0020_website_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="grantflow",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this website was fetched after GrantFlow request.",
                verbose_name="GrantFlow",
            ),
        ),
    ]
