# Generated by Django 5.2.5 on 2025-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0022_manualoutlinerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualoutlinerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="manualoutlinerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
