# Generated by Django 5.2.5 on 2025-08-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("answers", models.JSONField(default=dict)),
                ("sector", models.CharField(blank=True, max_length=160, null=True)),
                ("locale", models.CharField(blank=True, max_length=10, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("client_ip_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("total_questions", models.PositiveSmallIntegerField(default=5)),
                ("b_count", models.PositiveSmallIntegerField(default=0)),
                ("threshold_b", models.PositiveSmallIntegerField(default=0)),
                (
                    "redirected_to",
                    models.CharField(blank=True, choices=[(0, "Calendly"), (1, "Followup")], max_length=16, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contact", to="analytics.survey"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
