# Generated by Django 5.2.5 on 2025-08-11 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="b_count",
            new_name="threshold",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="redirected_to",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="threshold_b",
        ),
        migrations.RemoveField(
            model_name="survey",
            name="total_questions",
        ),
    ]
