# Generated by Django 5.2.5 on 2025-08-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_rename_b_count_survey_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="client_ip_hash",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Hashed Client's IP"),
        ),
        migrations.AlterField(
            model_name="survey",
            name="threshold",
            field=models.PositiveSmallIntegerField(default=0, help_text="The required amount of B answers for call."),
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                (
                    "appeared",
                    models.BooleanField(
                        default=False, help_text="Indicates whether the customer showed up for the meeting."
                    ),
                ),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="meeting", to="analytics.survey"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
