# Generated by Django 5.2.5 on 2025-08-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_survey_client_ip_hash_alter_survey_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="invitee_uri",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="uri",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
