# Generated by Django 5.2.5 on 2025-08-20 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_meeting_invitee_uri_meeting_uri"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="date",
            new_name="finish",
        ),
        migrations.AddField(
            model_name="meeting",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="start",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
