# Generated by Django 5.2.5 on 2025-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_rename_date_meeting_finish_meeting_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="finish",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start",
            field=models.DateTimeField(),
        ),
    ]
