# Generated by Django 5.2.5 on 2025-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0006_alter_meeting_finish_alter_meeting_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="firstname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="lastname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="timezone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
