# Generated by Django 5.2.5 on 2025-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0007_meeting_firstname_meeting_lastname_meeting_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="nickname",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
