# Generated by Django 5.2.5 on 2025-09-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0008_meeting_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notified",
            field=models.BooleanField(default=False, help_text="Indicates whether the contact has been notified."),
        ),
    ]
