# Generated by Django 5.2.5 on 2025-09-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0009_contact_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
