# Generated by Django 5.2.5 on 2025-09-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0010_survey_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="eager_to_pay",
            field=models.BooleanField(default=False, verbose_name="Eager To Pay"),
        ),
    ]
