# Generated by Django 5.2.5 on 2025-09-08 07:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0011_survey_eager_to_pay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="threshold",
        ),
    ]
