# Generated by Django 5.2.5 on 2025-09-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0012_remove_survey_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="geo_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
