# Generated by Django 5.2.5 on 2025-09-08 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0013_survey_geo_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="geo_location",
            new_name="geolocation",
        ),
    ]
