# Generated by Django 5.2.5 on 2025-09-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0014_rename_geo_location_survey_geolocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User Agent"),
        ),
    ]
