# Generated by Django 5.2.5 on 2025-11-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0015_alter_survey_user_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="active_subscription",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the contact has an active subscription."
            ),
        ),
    ]
