# Generated by Django 5.2.5 on 2025-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0016_contact_active_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="active_subscription",
            field=models.BooleanField(
                default=True, help_text="Indicates whether the contact has an active subscription."
            ),
        ),
    ]
