# Generated by Django 5.2.5 on 2025-09-22 15:50

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


def create_pgvector_extension(apps, schema_editor) -> None:
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'")
        if not cursor.fetchone():
            return
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(create_pgvector_extension, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("identifier", models.CharField(max_length=255, unique=True, verbose_name="Opportunity Number")),
                ("title", models.CharField(max_length=255, verbose_name="Opportunity Title")),
                ("code", models.CharField(max_length=255, verbose_name="Opportunity Code")),
                ("agency", models.CharField(max_length=255, verbose_name="Agency Name")),
                ("head", models.CharField(max_length=255, verbose_name="Top Level Agency Name")),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None, verbose_name="Categories"
                    ),
                ),
                ("opened", models.DateTimeField(verbose_name="Opening Date")),
                ("closed", models.DateTimeField(verbose_name="Closed Date")),
                ("instruction", models.TextField(blank=True, null=True, verbose_name="Submission Instruction")),
                ("archived", models.DateField(blank=True, null=True, verbose_name="Archiving Date")),
                ("awards", models.PositiveSmallIntegerField(verbose_name="Number of Awards")),
                ("funding", models.PositiveIntegerField(verbose_name="Estimated Program Funding")),
                (
                    "eligibility",
                    models.TextField(blank=True, null=True, verbose_name="Applicant Eligibility Description"),
                ),
                ("summary", models.TextField(blank=True, null=True, verbose_name="Summary Description")),
            ],
        ),
    ]
