# Generated by Django 5.2.5 on 2025-09-22 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Created At"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="vectorized",
            field=models.BooleanField(default=False),
        ),
    ]
