# Generated by Django 5.2.5 on 2025-09-22 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0002_opportunity_created_at_opportunity_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name="Categories"
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="closed",
            field=models.DateTimeField(verbose_name="Closing Date"),
        ),
    ]
