# Generated by Django 5.2.5 on 2025-09-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0003_alter_opportunity_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="awards",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Number of Awards"),
        ),
    ]
