# Generated by Django 5.2.5 on 2025-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0004_alter_opportunity_awards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="funding",
            field=models.PositiveBigIntegerField(verbose_name="Estimated Program Funding"),
        ),
    ]
