# Generated by Django 5.2.5 on 2025-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0005_alter_opportunity_funding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="funding",
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name="Estimated Program Funding"),
        ),
    ]
