# Generated by Django 5.2.5 on 2025-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0006_alter_opportunity_funding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="closed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Closing Date"),
        ),
    ]
