# Generated by Django 5.2.5 on 2025-09-25 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0007_alter_opportunity_closed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opportunity",
            options={"verbose_name": "Opportunity", "verbose_name_plural": "Opportunities"},
        ),
    ]
