# Generated by Django 5.2.5 on 2025-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0008_alter_opportunity_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="applications",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Total applications submitted.", null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="success_rate",
            field=models.FloatField(blank=True, help_text="Success rate for applications.", null=True),
        ),
    ]
