# Generated by Django 5.2.5 on 2025-10-01 04:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0009_opportunity_applications_opportunity_success_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="injection_date",
            field=models.DateField(
                default=datetime.datetime(2025, 10, 1, 4, 50, 36, 663335), verbose_name="Injection Date"
            ),
            preserve_default=False,
        ),
    ]
