# Generated by Django 5.2.5 on 2025-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0010_opportunity_injection_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="opened",
            field=models.DateField(verbose_name="Opening Date"),
        ),
    ]
