# Generated by Django 5.2.5 on 2025-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0011_alter_opportunity_opened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="closed",
            field=models.DateField(blank=True, null=True, verbose_name="Closing Date"),
        ),
    ]
