# Generated by Django 5.2.5 on 2025-10-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0012_alter_opportunity_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Opportunity URL"),
        ),
    ]
