# Generated by Django 5.2.5 on 2025-10-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0013_opportunity_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="link",
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name="Opportunity URL"),
        ),
    ]
