# Generated by Django 5.2.5 on 2025-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0014_alter_opportunity_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="injection_date",
            field=models.DateField(blank=True, null=True, verbose_name="Injection Date"),
        ),
    ]
